import os

DATABASE_DIR_PATH = os.path.join('database')
CUSTOMER_FILE_PATH = os.path.join(DATABASE_DIR_PATH, 'customer.csv')
ADDRESS_FILE_PATH = os.path.join(DATABASE_DIR_PATH, 'address.csv')
DRUGS_FILE_PATH = os.path.join(DATABASE_DIR_PATH, 'drugs.xlsx')

CUSTOMER_FIELDNAMES = ['ID', 'NAME', 'E-MAIL', 'PHONE', 'CREATED', 'UPDATED']
ADDRESS_FIELDNAMES = ['ID', 'STREET', 'CITY', 'COUNTRY']
DRUGS_FIELDNAMES = ['ID', 'DRUG', 'ON_RECEPT', 'NO_PACKAGES_AVAILABLE', 'DATE']
